require 'xsys/model/grouped_purchase_order_item'
require 'xsys/model/grouped_sale_item'
require 'xsys/model/price_list'
require 'xsys/model/product'
require 'xsys/model/product_category'
require 'xsys/model/product_provider'
require 'xsys/model/provider_kind'
require 'xsys/model/purchase_order_item'
require 'xsys/model/purchases_position'
require 'xsys/model/sale_item'
require 'xsys/model/sales_period'
require 'xsys/model/sales_position'
require 'xsys/model/seller'
require 'xsys/model/shop'
require 'xsys/model/stock'
require 'xsys/model/stock_control'
require 'xsys/model/stock_control_item'
require 'xsys/model/transaction'
require 'xsys/model/transaction_item'
require 'xsys/model/user'

require 'xsys/api'
require 'xsys/pagination'
require 'xsys/version'

# dependencies
require 'rest-client'
require 'singleton'
